"""
This type stub file was generated by pyright.
"""

import probly
from collections.abc import Iterable
from typing import Protocol, runtime_checkable
from lazy_dispatch import lazydispatch
from probly.predictor import Predictor, predict_raw
from probly.predictor._common import IterablePredictor

"""
This type stub file was generated by pyright.
"""
@runtime_checkable
class EnsemblePredictor[**In,Out](IterablePredictor[In, Out], Iterable[Predictor[In, Out]], Protocol):
    """Protocol for ensemble predictors."""
    @classmethod
    def __instancehook__(cls, instance: object) -> bool:
        ...
    


@lazydispatch
def ensemble_generator[**In,Out](base: Predictor[In, Out], num_members: int, reset_params: bool = ...) -> EnsemblePredictor[In, Out]:
    """Generate an ensemble from a base model."""
    ...
def ensemble[**In, Out](base: Predictor[In, Out], num_members: int, reset_params: bool = True, *, predictor_type: probly.predictor.PredictorName | type[probly.predictor.Predictor] | None = None) -> EnsemblePredictor[In, Out]: ...

@predict_raw.register(EnsemblePredictor)
def predict_list[**In,Out](predictor: EnsemblePredictor[In, Out], *args: In.args, **kwargs: In.kwargs) -> list[Out]:
    """Predict for a list of predictors."""
    ...

