"""
This type stub file was generated by pyright.
"""

from ._common import CredalBNNPredictor, credal_bnn

"""CredalBNN: Credal Bayesian Neural Networks for Uncertainty Estimation in Deep Learning."""
__all__ = ["CredalBNNPredictor", "credal_bnn"]
