"""
This type stub file was generated by pyright.
"""
import probly
from typing import Literal

from typing import Protocol, TYPE_CHECKING, runtime_checkable
from probly.method.ensemble import EnsemblePredictor
from probly.method.method import predictor_transformation
from probly.predictor import Predictor, ProbabilisticClassifier
from pytraverse import GlobalVariable

"""Shared CredalBNN implementation."""
if TYPE_CHECKING:
    ...
USE_BASE_WEIGHTS = GlobalVariable[bool]("USE_BASE_WEIGHTS", default=False)
POSTERIOR_STD = GlobalVariable[float]("POSTERIOR_STD", default=0.05)
PRIOR_MEAN = GlobalVariable[float]("PRIOR_MEAN", default=0)
PRIOR_STD = GlobalVariable[float]("PRIOR_STD", default=1)
NUM_MEMBERS = GlobalVariable[int]("NUM_MEMBERS", default=5)
@runtime_checkable
class CredalBNNPredictor[**In,Out](EnsemblePredictor[In, Out], Protocol):
    """A predictor that applies the Credal Bayesian Neural Network transformation."""
    ...
def credal_bnn[**In, Out](base: Predictor[In, Out], use_base_weights: bool = USE_BASE_WEIGHTS.default, posterior_std: float | list[float] | None = POSTERIOR_STD.default, prior_mean: float | list[float] | None = PRIOR_MEAN.default, prior_std: float | list[float] | None = PRIOR_STD.default, num_members: int = NUM_MEMBERS.default, *, predictor_type: Literal['categorical_distribution_predictor', 'probabilistic_classifier'] | type[probly.predictor.CategoricalDistributionPredictor] | None = None) -> CredalBNNPredictor[In, Out]: ...

