# @package method
name: "credal_relative_likelihood"
params:
  num_members: 10
  reset_params: true
train:
    alpha: 0.6
    batch_check: false # determines whether likelihood constraint is checked after batch (if true) or epoch (if false)
