defaults:
  - _self_
  - supervised_loss: cross_entropy
  - calibration: temperature_scaling
  - conformal: none
  - recipe: ???
  - method: ???

seed: 1
wandb:
  enabled: true
  entity: "probly"
  project: "test"

# models will always be saved in wandb, but this option controls whether they are also saved to disk
save_to_disk: false

amp: true
