defaults:
  - _self_
  - supervised_loss: cross_entropy
  - calibration: none
  - conformal: none
  - recipe: ???
  - method: ???

first_order_dataset: "cifar10h"
base_model: "resnet18"
seed: 1
batch_size: 512
amp: true
wandb:
  enabled: true
  entity: "probly"
  project: "cifar10-benchmark"
