defaults:
  - _self_
  - supervised_loss: cross_entropy
  - calibration: none
  - conformal: none
  - recipe: ???
  - method: ???

dataset: "cifar10"
base_model: "resnet18"
seed: 1
n_bins: 50
decomposition: "total"
loss: "zero_one"
batch_size: 512
amp: true
wandb:
  enabled: true
  entity: "probly"
  project: "test"
