dataset: "cifar10"
base_model: "resnet18"
pretrained: True
method:
    name: "bnn"
    samples: 1
epochs: 10
batch_size: 512
wandb: true
validate : true
# models will always be saved in wandb, but this option controls whether they are also saved to disk
save_to_disk: true

optimizer:
    name: "adam"
    params:
        lr: 0.001

scheduler:
  name: "plateau"
  params: {}

early_stopping:
  enabled: false
  patience: 5

grad_clip_norm: 1.0
amp: true
