dataset: "cifar10"
base_model: "resnet18"
pretrained: True
method:
    name: "bnn"
epochs: 10
batch_size: 32
wandb: true

optimizer:
    name: "adam"
    params:
        lr: 0.001

scheduler:
  name: "plateau"
  params: {}

early_stopping:
  enabled: false
  patience: 5

grad_clip_norm: 1.0
amp: true
