defaults:
  - _self_
  - method: ??? # user must specify a method.

seed: 1
dataset: "imagenet_shards"
base_model: "regnet_y_400mf"
pretrained: True
epochs: 5
batch_size: 1024
num_workers: 8
pin_memory: true
persistent_workers: true
prefetch_factor: 4
wandb:
  enabled: true
  entity: "probly"
  project: "test"
validate : true
# models will always be saved in wandb, but this option controls whether they are also saved to disk
save_to_disk: false

optimizer:
    name: "sgd"
    params:
        lr: 0.01
        momentum: 0.9
        weight_decay: 2e-5
        fused: true

scheduler:
  name: "cosine"
  params: {}

early_stopping:
  patience: 0  # set to > 0 to enable; number of epochs to wait without improvement

grad_clip_norm: 1.0
amp: true
