"""
This type stub file was generated by pyright.
"""

import probly
from typing import Literal, TYPE_CHECKING
from lazy_dispatch import lazydispatch
from probly.predictor import Predictor
from collections.abc import Callable
from lazy_dispatch.isinstance import LazyType

"""
This type stub file was generated by pyright.
"""
if TYPE_CHECKING:
    ...
@lazydispatch
def credal_net_generator[T: Predictor](base: T) -> T:
    """Generate a credal net from a base model."""
    ...

def register(cls: LazyType, generator: Callable) -> None:
    """Register a class which can be used as a base for a credal net."""
    ...
def credal_net[T: Predictor](base: T, *, predictor_type: Literal['categorical_distribution_predictor', 'probabilistic_classifier'] | type[probly.predictor.CategoricalDistributionPredictor] | None = None) -> T: ...

