"""
This type stub file was generated by pyright.
"""

import probly
from typing import Protocol, TYPE_CHECKING
from probly.predictor import Predictor, RandomPredictor
from pytraverse import GlobalVariable, lazydispatch_traverser
from lazy_dispatch.isinstance import LazyType
from pytraverse.composition import RegisteredLooseTraverser

"""
This type stub file was generated by pyright.
"""
if TYPE_CHECKING:
    ...
class BayesianPredictor[**In,Out](RandomPredictor[In, Out], Protocol):
    """A predictor that applies Bayesian layers."""
    ...


USE_BASE_WEIGHTS = GlobalVariable[bool]("USE_BASE_WEIGHTS", default=False)
POSTERIOR_STD = GlobalVariable[float]("POSTERIOR_STD", default=0.05)
PRIOR_MEAN = GlobalVariable[float]("PRIOR_MEAN", default=0)
PRIOR_STD = GlobalVariable[float]("PRIOR_STD", default=1)
bayesian_traverser = lazydispatch_traverser[object](name="bayesian_traverser")
def register(cls: LazyType, traverser: RegisteredLooseTraverser) -> None:
    """Register a class to be replaced by Bayesian layers."""
    ...
def bayesian[**In, Out](base: Predictor[In, Out], use_base_weights: bool = USE_BASE_WEIGHTS.default, posterior_std: float = POSTERIOR_STD.default, prior_mean: float = PRIOR_MEAN.default, prior_std: float = PRIOR_STD.default, *, predictor_type: probly.predictor.PredictorName | type[probly.predictor.Predictor] | None = None) -> BayesianPredictor[In, Out]: ...

