"""
This type stub file was generated by pyright.
"""

from ._common import CredalEnsemblingPredictor, credal_ensembling

"""Credal ensembling method."""
__all__ = ["CredalEnsemblingPredictor", "credal_ensembling"]
