"""
This type stub file was generated by pyright.
"""
import probly
from typing import Literal

from typing import Protocol, TYPE_CHECKING, runtime_checkable
from probly.method.ensemble import EnsembleCategoricalDistributionPredictor
from probly.method.method import predictor_transformation
from probly.predictor import Predictor, ProbabilisticClassifier
from probly.representation.distribution import CategoricalDistribution

"""Shared credal ensembling implementation."""
if TYPE_CHECKING:
    ...
@runtime_checkable
class CredalEnsemblingPredictor[**In,Out: CategoricalDistribution](EnsembleCategoricalDistributionPredictor[In, Out], Protocol):
    """A predictor that applies the credal ensembling representer."""
    ...
def credal_ensembling[**In, Out: CategoricalDistribution](base: Predictor[In, Out], num_members: int, reset_params: bool = True, *, predictor_type: Literal['categorical_distribution_predictor', 'probabilistic_classifier'] | type[probly.predictor.CategoricalDistributionPredictor] | None = None) -> CredalEnsemblingPredictor[In, Out]: ...

