repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.10.10
    hooks:
        - id: uv-lock
          priority: 0
    # zizmor detects security vulnerabilities in GitHub Actions workflows.
    # Additional configuration for the tool is found in `.github/zizmor.yml`
  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    rev: v1.23.1
    hooks:
         - id: zizmor
           priority: 0
           args: [--min-severity=low]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-json
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: check-merge-conflict
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.11
    hooks:
      - id: ruff-check
        args: [--fix, --exit-non-zero-on-fix, --no-cache]
      - id: ruff-format
        args: [--verbose]

# Local hook for ty until it's available in pre-commit
  - repo: local
    hooks:
    -   id: sigx-generate
        name: sigx-generate
        language: system
        entry: uv run python scripts/generate_method_stubs.py
        pass_filenames: false
        files: ^src/probly/method(?:/[^/]+/_common\.py|/method\.py|/_sigx_transforms\.py)$
    -   id: ty-check
        name: ty-check
        language: system
        entry: uv run python scripts/run_ty_check.py
        pass_filenames: false
