"""
This type stub file was generated by pyright.
"""

from probly import calibration as calibration, datasets as datasets, evaluation as evaluation, layers as layers, method as method, plot as plot, predictor as predictor, quantification as quantification, representation as representation, representer as representer, train as train, traverse_nn as traverse_nn, utils as utils

"""probly: Uncertainty Representation and Quantification for Machine Learning."""
__version__ = ...
