"""
This type stub file was generated by pyright.
"""

from ._common import CredalWrapperPredictor, credal_wrapper

"""Credal wrapper method."""
__all__ = ["CredalWrapperPredictor", "credal_wrapper"]
