"""
This type stub file was generated by pyright.
"""
import probly
from typing import Literal

from typing import Protocol, TYPE_CHECKING
from probly.method.ensemble import EnsemblePredictor
from probly.method.method import predictor_transformation
from probly.predictor import Predictor, ProbabilisticClassifier

"""Shared credal wrapper implementation."""
if TYPE_CHECKING:
    ...
class CredalWrapperPredictor[**In,Out](EnsemblePredictor[In, Out], Protocol):
    """A predictor that applies the credal wrapper representer."""
    ...
def credal_wrapper[**In, Out](base: Predictor[In, Out], num_members: int, reset_params: bool = True, *, predictor_type: Literal['categorical_distribution_predictor', 'probabilistic_classifier'] | type[probly.predictor.CategoricalDistributionPredictor] | None = None) -> EnsemblePredictor[In, Out]: ...

