"""
This type stub file was generated by pyright.
"""

import probly
from typing import Literal, Protocol, TYPE_CHECKING
from probly.method.ensemble import EnsemblePredictor
from probly.predictor import Predictor

"""
This type stub file was generated by pyright.
"""
if TYPE_CHECKING:
    ...
class CredalRelativeLikelihoodPredictor[**In,Out](EnsemblePredictor[In, Out], Protocol):
    """A predictor that applies the credal relative likelihood transformation."""
    ...
def credal_relative_likelihood[**In, Out](base: Predictor[In, Out], num_members: int, reset_params: bool = True, *, predictor_type: Literal['categorical_distribution_predictor', 'probabilistic_classifier'] | type[probly.predictor.CategoricalDistributionPredictor] | None = None) -> CredalRelativeLikelihoodPredictor[In, Out]: ...

