"""
This type stub file was generated by pyright.
"""

from probly.lazy_types import TORCH_MODULE
from ._common import credal_net, credal_net_generator, register

"""Credal net implementation for uncertainty quantification."""
@credal_net_generator.delayed_register(TORCH_MODULE)
def _(_: type) -> None:
    ...

__all__ = ["credal_net", "register"]
