"""
This type stub file was generated by pyright.
"""

from probly.lazy_types import FLAX_MODULE, TORCH_MODULE
from ._common import DropoutPredictor, dropout, dropout_traverser, register

"""Dropout ensemble implementation for uncertainty quantification."""
@dropout_traverser.delayed_register(TORCH_MODULE)
def _(_: type) -> None:
    ...

@dropout_traverser.delayed_register(FLAX_MODULE)
def _(_: type) -> None:
    ...

__all__ = ["DropoutPredictor", "dropout", "dropout_traverser", "register"]
