"""
This type stub file was generated by pyright.
"""
import probly

from typing import Protocol, TYPE_CHECKING, runtime_checkable
from probly.method.method import predictor_transformation
from probly.predictor import Predictor, RandomPredictor
from pytraverse import GlobalVariable, lazydispatch_traverser
from flax.nnx.rnglib import RngStream, Rngs
from lazy_dispatch.isinstance import LazyType
from pytraverse.composition import RegisteredLooseTraverser

"""Shared dropout implementation."""
if TYPE_CHECKING:
    ...
@runtime_checkable
class DropoutPredictor[**In,Out](RandomPredictor[In, Out], Protocol):
    """A predictor that applies dropout."""
    ...


P = GlobalVariable[float]("P", "The probability of dropout.")
RNG = int | Rngs | RngStream
RNGS = GlobalVariable[RNG]("RNGS", "rngs for flax layer initialization.")
RNG_COLLECTION = GlobalVariable[str]("RNG_COLLECTION", "rng_collection for flax layer initialization")
dropout_traverser = lazydispatch_traverser[object](name="dropout_traverser")
def register(cls: LazyType, traverser: RegisteredLooseTraverser) -> None:
    """Register a class to be prepended by Dropout layers."""
    ...
def dropout[T: Predictor](base: T, p: float = 0.25, rng_collection: str = 'dropout', rngs: Rngs | RngStream | int = 1, *, predictor_type: probly.predictor.PredictorName | type[probly.predictor.Predictor] | None = None) -> T: ...

