"""
This type stub file was generated by pyright.
"""

from probly.lazy_types import FLAX_MODULE, TORCH_MODULE
from ._common import SubensemblePredictor, subensemble, subensemble_generator

"""Subensemble implementation for uncertainty quantification."""
@subensemble_generator.delayed_register(TORCH_MODULE)
def _(_: type) -> None:
    ...

@subensemble_generator.delayed_register(FLAX_MODULE)
def _(_: type) -> None:
    ...

__all__ = ["SubensemblePredictor", "subensemble", "subensemble_generator"]
