"""
This type stub file was generated by pyright.
"""
import probly

from typing import Any, Protocol, TYPE_CHECKING, runtime_checkable
from lazy_dispatch import lazydispatch
from probly.method.ensemble import EnsemblePredictor
from probly.method.method import predictor_transformation
from probly.predictor import Predictor

"""
This type stub file was generated by pyright.
"""
if TYPE_CHECKING:
    ...
@runtime_checkable
class SubensemblePredictor[**In,Out](EnsemblePredictor[In, Out], Protocol):
    """Protocol for subensemble predictors."""
    @classmethod
    def __instancehook__(cls, instance: object) -> bool:
        ...
    


@lazydispatch
def subensemble_generator[**In,H,Out](base: Predictor[In, H], *args: Any, **kwargs: Any) -> SubensemblePredictor[In, Out]:
    """Generate a subensemble from a base model."""
    ...
def subensemble[**In, H, Out](base: Predictor[In, H], num_heads: int, head: Predictor[[H], Out] | None = None, reset_params: bool = True, head_layer: int = 1, *, predictor_type: probly.predictor.PredictorName | type[probly.predictor.Predictor] | None = None) -> SubensemblePredictor[In, Out]: ...

