"""
This type stub file was generated by pyright.
"""

from probly.lazy_types import FLAX_MODULE, TORCH_MODULE
from ._common import batchensemble, batchensemble_traverser, register

"""Batchensemble implementation for uncertainty quantification."""
@batchensemble_traverser.delayed_register(TORCH_MODULE)
def _(_: type) -> None:
    ...

@batchensemble_traverser.delayed_register(FLAX_MODULE)
def _(_: type) -> None:
    ...

__all__ = ["batchensemble", "batchensemble_traverser", "register"]
