"""
This type stub file was generated by pyright.
"""
import probly

from typing import TYPE_CHECKING
from probly.method.method import predictor_transformation
from pytraverse import GlobalVariable, lazydispatch_traverser
from flax.nnx.rnglib import Rngs
from lazy_dispatch.isinstance import LazyType
from probly.predictor import Predictor
from pytraverse.composition import RegisteredLooseTraverser

"""
This type stub file was generated by pyright.
"""
if TYPE_CHECKING:
    ...
NUM_MEMBERS = GlobalVariable[int]("NUM_MEMBERS", default=1)
USE_BASE_WEIGHTS = GlobalVariable[bool]("USE_BASE_WEIGHT", default=False)
S_MEAN = GlobalVariable[float]("S_MEAN", default=1)
S_STD = GlobalVariable[float]("S_STD", default=0.01)
R_MEAN = GlobalVariable[float]("R_MEAN", default=1)
R_STD = GlobalVariable[float]("R_STD", default=0.01)
RNG = Rngs | int
RNGS = GlobalVariable[RNG]("RNGS", "rngs for flax layer initialization.", default=1)
batchensemble_traverser = lazydispatch_traverser[object](name="batchensemble_traverser")
def register(cls: LazyType, traverser: RegisteredLooseTraverser) -> None:
    """Register a class to be replaced by Batchensemble layers."""
    ...
def batchensemble[T: Predictor](base: T, num_members: int = NUM_MEMBERS.default, use_base_weights: bool = USE_BASE_WEIGHTS.default, s_mean: float = S_MEAN.default, s_std: float = S_STD.default, r_mean: float = R_MEAN.default, r_std: float = R_STD.default, rngs: Rngs | int = RNGS.default, *, predictor_type: probly.predictor.PredictorName | type[probly.predictor.Predictor] | None = None) -> T: ...

