"""
This type stub file was generated by pyright.
"""

from probly.lazy_types import TORCH_MODULE
from ._common import DDUPredictor, ddu, ddu_generator

"""Deep Deterministic Uncertainty (DDU) for classification models."""
@ddu_generator.delayed_register(TORCH_MODULE)
def _(_: type) -> None:
    ...

__all__ = ["DDUPredictor", "ddu"]
