"""
This type stub file was generated by pyright.
"""
import probly
from typing import Literal

from typing import Protocol, runtime_checkable
from lazy_dispatch import lazydispatch
from probly.method.method import predictor_transformation
from probly.predictor import Predictor, ProbabilisticClassifier

"""Shared DDU implementation."""
@runtime_checkable
class DDUPredictor[**In,Out](Predictor[In, Out], Protocol):
    """A predictor that applies the credal wrapper representer."""
    encoder: Predictor[In, Out]
    classification_head: Predictor[In, Out]
    density_head: Predictor[In, Out]
    ...


@lazydispatch
def ddu_generator[**In,Out](base: Predictor[In, Out], sn_coeff: float) -> DDUPredictor[In, Out]:
    """Generate a DDU model from a base model."""
    ...
def ddu[**In, Out](base: Predictor[In, Out], sn_coeff: float = 3.0, *, predictor_type: Literal['categorical_distribution_predictor', 'probabilistic_classifier'] | type[probly.predictor.CategoricalDistributionPredictor] | None = None) -> DDUPredictor[In, Out]: ...

