"""====================================================
Cyclone forecast uncertainty with WeatherNext
====================================================

WeatherNext (https://github.com/google-deepmind/weathernext) is Google DeepMind's family of global weather
forecasting models. Its FGN models are generative: a single checkpoint defines a predictive distribution
that is accessed by sampling, one ensemble member per random key (there is deliberately no closed-form
single-pass distribution; sampling is the model's distribution interface). The WeatherNext integration
wraps such a model as a probly predictor, so ``representer`` collects members and probly quantifies
per-grid-cell forecast uncertainty.

The scenario is Hurricane Milton (initialization 2024-10-07, landfall in Florida on 2024-10-09), forecast
72 hours ahead. Compared head-to-head at identical compute (eight forward rollouts each):

* the **single-model distribution**: one checkpoint, eight samples of its learned generative noise;
* a **checkpoint ensemble**: two independently trained checkpoints, four samples each, adding epistemic
  weight-space diversity;
* two **single-forecast heuristics** that need no distribution at all (strong winds and sharp gradients
  are hard to predict), plus random rejection.

This example is not executed in the documentation build: it requires the ``weathernext`` package and its
dependencies (JAX, haiku, xarray) and a GPU. The figure below was generated by this exact script on two
A40 GPUs in a few minutes:

.. image:: /_static/weathernext_uncertainty.png
   :alt: Hurricane Milton wind forecast, uncertainty maps, and selective prediction curves.

Set ``WEATHERNEXT_DATA`` to the directory holding the ~1GB of public downloads:

.. code-block:: bash

    BASE=https://storage.googleapis.com/dm_graphcast/weathernext2
    curl -o wn_mini_2024.npz "$BASE/params/WeatherNextCyclones_Mini_%3C2024.npz"
    curl -o wn_mini_2023.npz "$BASE/params/WeatherNextCyclones_Mini_%3C2023.npz"
    curl -o hres_1deg_steps12.nc \
        "$BASE/dataset/source-hres_forecast_init-2024-10-07%2000%3A00%3A00_res-1.0_levels-13_steps-12.nc"
"""

from __future__ import annotations

# sphinx_gallery_thumbnail_path = '_static/weathernext_uncertainty.png'
import dataclasses
import os

import haiku as hk
import jax
import matplotlib.pyplot as plt
import numpy as np
import xarray
import xarray_jax
from weathernext.utils import checkpoint, data_utils, fiddle_config_io, rollout
from weathernext.weathernext2 import fgn

from probly.evaluation.selective_prediction import selective_prediction
from probly.integrations.weathernext import WeatherNextPredictor
from probly.quantification import quantify
from probly.representer import representer

DATA_DIR = os.environ.get("WEATHERNEXT_DATA", ".")
NUM_MEMBERS = 8

# %%
# Load the model and Hurricane Milton initial conditions
# ------------------------------------------------------

example_batch = xarray.load_dataset(f"{DATA_DIR}/hres_1deg_steps12.nc").compute()
config = fiddle_config_io.get_fiddle_config_by_name("weathernext2/configs/WeatherNextCyclones_Mini")
checkpoints = {}
for name, path in [("2024", f"{DATA_DIR}/wn_mini_2024.npz"), ("2023", f"{DATA_DIR}/wn_mini_2023.npz")]:
    with open(path, "rb") as f:
        checkpoints[name] = checkpoint.load(f, fgn.CheckPoint)

eval_inputs, eval_targets, eval_forcings = data_utils.extract_inputs_targets_forcings(
    example_batch,
    target_lead_times=slice("6h", f"{(example_batch.sizes['time'] - 2) * 6}h"),
    **dataclasses.asdict(config.task),
)

# %%
# Build the jitted forecast function (from the WeatherNext demo)
# --------------------------------------------------------------

transformer_kwargs = config.predictor_kwargs["noisy_function_kwargs"]["mesh_model_ctor"].keywords[
    "transformer_kwargs"
]
if jax.default_backend() == "gpu":
    transformer_kwargs["attention_type"] = "triblockdiag_mha"

config_inference = fgn.PredictorConfig(
    task=config.task,
    predictor_constructor=config.predictor_constructor,
    predictor_kwargs=config.predictor_kwargs,
    predictor_wrappers=config.predictor_wrappers[:-1],  # remove the ensemble wrapper
)


@hk.transform
def run_forward(inputs, targets_template, forcings):
    predictor = fgn.construct_predictor(config_inference)
    return predictor(inputs, targets_template=targets_template, forcings=forcings)


run_forward_params = jax.jit(lambda params, rng, i, t, f: run_forward.apply(params, rng, i, t, f))


# %%
# Wrap the model as a probly predictor
# ------------------------------------
#
# ``make_ensemble_fn`` builds a bulk forecast function: members are split evenly
# across the given checkpoints (one checkpoint gives the single-model generative
# distribution, two give a checkpoint ensemble) and rolled out with the pmapped
# WeatherNext machinery, parallelized across the available GPUs.


def make_ensemble_fn(member_params):
    def ensemble_fn(seeds, inputs, targets_template, forcings):
        member_forecasts = []
        for which, params in enumerate(member_params):
            member_seeds = [seed for i, seed in enumerate(seeds) if i % len(member_params) == which]
            rngs = np.stack([jax.random.fold_in(jax.random.PRNGKey(0), seed) for seed in member_seeds])
            member_fn = lambda rng, i, t, f: run_forward_params(params, rng, i, t, f)  # noqa: B023, E731
            chunks = []
            for chunk in rollout.chunked_prediction_generator_multiple_runs(
                predictor_fn=xarray_jax.pmap(member_fn, dim="sample"),
                rngs=rngs,
                inputs=inputs,
                targets_template=targets_template,
                forcings=forcings,
                num_steps_per_chunk=1,
                num_samples=len(member_seeds),
                pmap_devices=jax.local_devices(),
            ):
                # Block on the chunk and move it to host memory: keeping device-backed chunks makes the
                # later xarray combine dispatch a storm of tiny GPU ops that is orders of magnitude slower.
                jax.block_until_ready([xarray_jax.unwrap_data(chunk[var]) for var in chunk.data_vars])
                chunks.append(chunk.as_numpy())
                print(f"forecast chunk {len(chunks)} (params {which}) done", flush=True)
            member_forecasts.append(xarray.combine_by_coords(chunks))
        combined = xarray.concat(member_forecasts, dim="sample")
        return combined.isel(batch=0)

    return ensemble_fn


single_model = WeatherNextPredictor(ensemble_fn=make_ensemble_fn([checkpoints["2024"].params]))
checkpoint_ensemble = WeatherNextPredictor(
    ensemble_fn=make_ensemble_fn([checkpoints["2024"].params, checkpoints["2023"].params])
)

samples_single = representer(single_model, num_samples=NUM_MEMBERS).represent(
    eval_inputs, eval_targets * np.nan, eval_forcings
)
samples_ckpt = representer(checkpoint_ensemble, num_samples=NUM_MEMBERS).represent(
    eval_inputs, eval_targets * np.nan, eval_forcings
)

# %%
# Quantify forecast uncertainty per grid cell
# -------------------------------------------


def wind_members_and_uncertainty(sample_dict):
    u10, v10 = sample_dict["10m_u_component_of_wind"], sample_dict["10m_v_component_of_wind"]
    members = np.sqrt(u10.array**2 + v10.array**2)  # (members, time, lat, lon)
    uncertainty = np.asarray(quantify(type(u10)(members, sample_axis=0))["total"])  # (time, lat, lon)
    return members, uncertainty


wind_members, wind_uncertainty = wind_members_and_uncertainty(samples_single)
wind_mean = wind_members.mean(axis=0)
ckpt_members, ckpt_uncertainty = wind_members_and_uncertainty(samples_ckpt)

target_wind = np.sqrt(
    eval_targets["10m_u_component_of_wind"].isel(batch=0).values ** 2
    + eval_targets["10m_v_component_of_wind"].isel(batch=0).values ** 2
)

# %%
# Uncertainty is informative: selective prediction on grid cells
# --------------------------------------------------------------
#
# Using each uncertainty signal as rejection criterion, discarding the most
# uncertain cells should lower the wind forecast error. All criteria reject
# cells of the same single-model ensemble-mean forecast, isolating the value of
# the uncertainty signal itself.

t = wind_members.shape[1] - 1  # last lead time
errors = np.abs(wind_mean[t] - target_wind[t]).ravel()

single_forecast = wind_members[0, t]  # what one forward pass provides
gradient = np.hypot(*np.gradient(single_forecast))
rng = np.random.default_rng(0)
criteria = {
    "single-model distribution (1 ckpt x 8 samples)": wind_uncertainty[t].ravel(),
    "checkpoint ensemble (2 ckpts x 4 samples)": ckpt_uncertainty[t].ravel(),
    "single-forecast wind magnitude": single_forecast.ravel(),
    "single-forecast gradient": gradient.ravel(),
    "random": rng.permutation(len(errors)).astype(float),
}
curves = {name: selective_prediction(criterion, errors, n_bins=50) for name, criterion in criteria.items()}
for name, (aurc, _) in curves.items():
    print(f"AURC {name}: {aurc:.4f}")

# %%
# Visualize Hurricane Milton forecast uncertainty
# -----------------------------------------------

lat, lon = example_batch.lat.values, example_batch.lon.values
lat_mask, lon_mask = (lat >= 10) & (lat <= 40), (lon >= 255) & (lon <= 300)
extent = [lon[lon_mask].min(), lon[lon_mask].max(), lat[lat_mask].min(), lat[lat_mask].max()]
origin = "lower" if lat[0] < lat[-1] else "upper"


def crop(a: np.ndarray) -> np.ndarray:
    return a[..., lat_mask, :][..., lon_mask]


lead = (t + 1) * 6
fig, axes = plt.subplot_mosaic([["target", "mean", "single_unc"], ["ckpt_unc", "curves", "curves"]], figsize=(16, 8))
panels = [
    ("target", crop(target_wind[t]), f"HRES target 10m wind, +{lead}h [m/s]", "viridis"),
    ("mean", crop(wind_mean[t]), "WeatherNext ensemble mean", "viridis"),
    ("single_unc", crop(wind_uncertainty[t]), "single-model distribution uncertainty", "magma"),
    ("ckpt_unc", crop(ckpt_uncertainty[t]), "checkpoint ensemble uncertainty", "magma"),
]
for key, data, title, cmap in panels:
    im = axes[key].imshow(data, origin=origin, extent=extent, cmap=cmap)
    axes[key].set_title(title)
    fig.colorbar(im, ax=axes[key], shrink=0.8)

for name, (aurc, risks) in curves.items():
    coverage = 1 - np.arange(len(risks)) / len(risks)
    axes["curves"].plot(coverage, risks, label=f"{name} (AURC {aurc:.3f})")
axes["curves"].set_xlabel("coverage (fraction of grid cells kept)")
axes["curves"].set_ylabel("mean 10m wind error [m/s]")
axes["curves"].set_title("Selective prediction on grid cells")
axes["curves"].legend()
axes["curves"].invert_xaxis()

fig.suptitle(f"Hurricane Milton, WeatherNext Cyclones Mini x probly ({NUM_MEMBERS} forwards per method)")
fig.tight_layout()
fig.savefig("weathernext_uncertainty.png", dpi=150)
plt.show()
