"""
This type stub file was generated by pyright.
"""

from ._common import CredalRelativeLikelihoodPredictor, credal_relative_likelihood

"""Credal relative likelihood method."""
__all__ = ["CredalRelativeLikelihoodPredictor", "credal_relative_likelihood"]
