"""
This type stub file was generated by pyright.
"""

from probly.lazy_types import FLAX_LIST, FLAX_MODULE, SKLEARN_MODULE, TORCH_MODULE, TORCH_MODULE_LIST
from ._common import EnsembleCategoricalDistributionPredictor, EnsembleDirichletDistributionPredictor, EnsemblePredictor, ensemble, ensemble_generator

"""
This type stub file was generated by pyright.
"""
@ensemble_generator.delayed_register(TORCH_MODULE)
def _(_: type) -> None:
    ...

@ensemble_generator.delayed_register(TORCH_MODULE)
def _(_: type) -> None:
    ...

@ensemble_generator.delayed_register(FLAX_MODULE)
def _(_: type) -> None:
    ...

@ensemble_generator.delayed_register(SKLEARN_MODULE)
def _(_: type) -> None:
    ...

__all__ = ["EnsembleCategoricalDistributionPredictor", "EnsembleDirichletDistributionPredictor", "EnsemblePredictor", "ensemble", "ensemble_generator"]
