"""
This type stub file was generated by pyright.
"""

from probly.lazy_types import TORCH_MODULE
from ._common import BayesianPredictor, bayesian, bayesian_traverser, register

"""Bayesian implementation for uncertainty quantification."""
@bayesian_traverser.delayed_register(TORCH_MODULE)
def _(_: type) -> None:
    ...

__all__ = ["BayesianPredictor", "bayesian", "register"]
