"""
This type stub file was generated by pyright.
"""

from probly.lazy_types import FLAX_MODULE, TORCH_MODULE
from ._common import dropconnect, dropconnect_traverser, register

"""DropConnect implementation for uncertainty quantification."""
@dropconnect_traverser.delayed_register(TORCH_MODULE)
def _(_: type) -> None:
    ...

@dropconnect_traverser.delayed_register(FLAX_MODULE)
def _(_: type) -> None:
    ...

__all__ = ["dropconnect", "dropconnect_traverser", "register"]
