# @package _global_
dataset: "cifar10"
base_model: "resnet18"
pretrained: False
epochs: 50
batch_size: 2048
num_workers: 16
pin_memory: true
persistent_workers: true
optimizer:
    name: "sgd"
    params:
        lr: 0.01
        momentum: 0.9
        weight_decay: 5e-4
        fused: true

scheduler:
  name: "warmup_cosine"
  params:
    warmup_epochs: 5
    warmup_start_factor: 0.1  # we start at 10% of optimizer.params.lr
    min_lr: 1e-6  # lr goes down to 1e-6 at end of training

early_stopping:
  patience: 5  # set to > 0 to enable; number of epochs to wait without improvement
