name: Docs CI

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  doc_build:
    name: Test Documentation Build
    uses: ./.github/workflows/_docs-build.yml
    with:
      strict: true
