name: Lower Bounds CI

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lower_bounds_tests:
    name: Lower Bounds (${{ matrix.dependency-group }})
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            dependency-group: torch
          - os: ubuntu-latest
            dependency-group: jax
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          persist-credentials: false
      - name: Run tests with minimum dependency versions
        uses: ./.github/actions/run-tests
        with:
          python-version: "3.13"
          dependency-group: ${{ matrix.dependency-group }}
          resolution: "lowest-direct"
          coverage: "false"
