# Deploy docs to GitHub Pages
name: Deploy Docs

on:
  push:
    branches: [main]

jobs:
  build:
    uses: ./.github/workflows/_docs-build.yaml
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download docs artifact
        uses: actions/download-artifact@v4
        with:
          name: sphinx-docs
          path: docs/build/html
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html
          enable_jekyll: false
