name: Install & Import probly

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  install-and-import:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv and Python
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.11"

      - name: Install package using uv
        run: uv pip install .

      - name: Test import
        run: uv run python -c "import importlib.metadata; import probly; print(importlib.metadata.version("probly")); print('✅ probly imported successfully')"
